{
 "title": "Hospital SIEM Overview",
 "tags": [
  "hospital",
  "siem",
  "grafana-stack"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total alerts last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"hospital-api\", severity=\"HIGH\"}[24h])"
    }
   ]
  },
  {
   "title": "Critical IoT anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"iot-gateway\"} |= \"EMERGENCY\" [1h]))"
    }
   ]
  },
  {
   "title": "Login failures over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"hospital-api\"} |= \"LOGIN_FAILED\" [5m])"
    }
   ]
  },
  {
   "title": "Top attacking IPs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (source_ip) (count_over_time({job=\"hospital-api\"} | json | source_ip != \"\" [1h])))"
    }
   ]
  },
  {
   "title": "Live security events stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"hospital-api\"} | json | severity =~ \"HIGH|CRITICAL\""
    }
   ]
  }
 ]
}